FROM ubuntu:24.04

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      systemd \
      systemd-sysv \
      procps \
      iproute2 \
      ca-certificates \
      tzdata \
 && rm -rf /var/lib/apt/lists/*

CMD ["/lib/systemd/systemd"]
